#
# Spring Properties
#
server:
  servlet:
    context-path: /turbodepot-api

spring:
  application:
    name: turbodepot-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://${turbodepot-api.datasource.host}:${turbodepot-api.datasource.port}/${turbodepot-api.datasource.database}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
        cache:
          use_query_cache: false
        generate_statistics: false
    open-in-view: false
  flyway:
    locations: classpath:db/migration/turbodepot-api
    baseline-on-migrate: true
    table: _schema_version_turbodepot_api

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

#
# Custom application properties
#
turbodepot-api:
  datasource:
    port: 3306
